# MCP Server
camel.server.port = 9091
camel.server.enabled = true
camel.server.mcp-enabled = true
camel.server.mcp-tags = all
camel.server.mcp-server-name = my-integration-app

# Datasource
forage.jdbc.db.kind=postgresql
forage.jdbc.url=jdbc:postgresql://postgres:5432/labdb
forage.jdbc.username=user1
forage.jdbc.password=QXPC9oYvQ6EM

# S3 access
camel.component.aws2-s3.accessKey=deLfxv2vkCcUREgbvkNG
camel.component.aws2-s3.secretKey=or0cmGku0o4+m3nSm0XEXflJsCKVtXGwtheBHYHE
camel.component.aws2-s3.uriEndpointOverride=https://s3-openshift-storage.apps.cluster-z2wxs.dyn.redhatworkshops.io

# S3 bucket
s3.bucket=user1

# OpenAI Amend agent
camel.component.openai.model=qwen3-14b
camel.component.openai.baseUrl=https://maas-rhdp.apps.maas.redhatworkshops.io/v1
# camel.component.openai.apiKey=sk-gxg-DmSTi6Mi0UFCVc8yRQ
camel.component.openai.apiKey=sk-6QcK9dbyxBc9NQzj5zxerQ

# Helpdesk credentials
helpdesk.url=https://helpdesk-helpdesk.apps.cluster-z2wxs.dyn.redhatworkshops.io
helpdesk.username=user1
helpdesk.password=QXPC9oYvQ6EM
helpdesk.group.id=6a857f4b7bf01f2f674c52d2
helpdesk.type.id.issue=6a857cc4657b12d92e1cb95c
helpdesk.priority.id.normal=6a857ced7bf01f2f674c51f1

